[phases.setup]
nixPkgs = [
  "php83",
  "php83Extensions.pdo",
  "php83Extensions.pdo_mysql",
  "php83Extensions.mbstring",
  "php83Extensions.xml",
  "php83Extensions.zip",
  "php83Extensions.gd",
  "php83Extensions.curl",
  "php83Extensions.tokenizer",
  "php83Extensions.bcmath",
  "php83Extensions.fileinfo",
  "php83Extensions.opcache",
  "composer",
  "nodejs_20",
  "nodePackages.npm"
]

[phases.install]
cmds = [
  "composer install --no-dev --optimize-autoloader --no-interaction",
  "npm ci",
  "npm run build"
]

[start]
cmd = "bash start.sh"
